development: &default
  adapter: postgresql
  database: foodzone_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  reaping_frequency: 10
  timeout: 5000

test:
  <<: *default
  database: foodzone_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

staging: *deploy
